backend:
  name: git-gateway
  branch: main

media_folder: "images"        # Onde os uploads ficam salvos no repositório
public_folder: "/images"      # Caminho público dos uploads
locale: "pt"

collections:

  # =======================
  # TEMA (cores, botões, seções)
  # Arquivo: content/theme.json
  # =======================
  - name: theme
    label: "Tema (cores, botões, seções)"
    delete: false
    files:
      - file: "content/theme.json"
        name: theme
        label: "Configurações do Tema"
        format: json
        fields:
          # CORES (campos no RAIZ do theme.json, sem objeto aninhado)
          - { label: "Cor dos botões (CTA)",            name: buttonColor,    widget: color, allowInput: true, default: "#97af7d",  hint: "Usada nos botões como 'Fazer pedido'." }
          - { label: "Cor dos títulos/links (destaque)", name: primaryColor,   widget: color, allowInput: true, default: "#58410d",  hint: "Títulos, links e elementos de destaque." }
          - { label: "Cor de detalhes menores (opc.)",   name: secondary,      widget: color, allowInput: true, default: "#7a5c4b",  required: false }
          - { label: "Fundo geral do site",              name: bg,             widget: color, allowInput: true, default: "#f8f6f3" }
          - { label: "Cor do texto principal",           name: text,           widget: color, allowInput: true, default: "#5a4b42" }
          - { label: "Fundo das caixinhas (cards)",      name: card,           widget: color, allowInput: true, default: "#ffffff" }
          # Mantidos por compatibilidade (opc.)
          - { label: "Cor primária (backup, opc.)",      name: primary,        widget: color, allowInput: true, default: "#d9a5a0",  required: false }
          - { label: "Cor de fundo alternativa (opc.)",  name: backgroundColor,widget: color, allowInput: true, default: "#e4e4d3",  required: false }

          # BOTÃO DO TOPO
          - label: "Botão do topo (Header)"
            name: headerCta
            widget: object
            collapsed: true
            fields:
              - { label: "Texto do botão", name: label, widget: string, required: false, default: "Pedir no WhatsApp" }
              - { label: "Link do botão",  name: href,  widget: string, required: false, default: "https://wa.me/xx?text=Ol%C3%A1%20quero%20fazer%20um%20pedido" }

          # MARCA / WHATSAPP (opcionais, ficam em branco para cada aluna preencher)
          - { label: "Marca (texto no topo)", name: brandText,       widget: string, required: false, default: "Vanilla Cake Studio" }
          - { label: "WhatsApp (com DDI)",    name: whatsapp,        widget: string, required: false, hint: "Ex.: +55 11 91234-5678" }
          - { label: "Mensagem padrão WhatsApp", name: whatsappMessage, widget: text, required: false, hint: "Texto que vai junto no link." }

          # LIGA/DESLIGA SEÇÕES
          - { label: "Mostrar a seção 'Sobre'", name: showAbout, widget: boolean, default: true, required: false }
          - label: "Seções visíveis"
            name: sectionsEnabled
            widget: object
            fields:
              - { label: "Banner (Hero)",     name: hero,         widget: boolean, default: true }
              - { label: "Sobre",             name: about,        widget: boolean, default: true }
              - { label: "Cardápio",          name: menu,         widget: boolean, default: true }
              - { label: "Decorações",        name: decorations,  widget: boolean, default: true }
              - { label: "Galeria (opcional)",name: gallery,      widget: boolean, default: false }
              - { label: "Personalizado",     name: custom,       widget: boolean, default: true }
              - { label: "Informações",       name: policies,     widget: boolean, default: true }
              - { label: "FAQ",               name: faq,          widget: boolean, default: true }

          # ORDEM DAS SEÇÕES (com rótulos legíveis)
          - label: "Ordem das seções (arraste para reordenar)"
            name: sectionsOrder
            widget: list
            allow_add: false
            default: ["hero","about","menu","decorations","custom","policies","faq"]
            field:
              label: "Seção"
              name: item
              widget: select
              options:
                - { label: "Banner (Hero)", value: "hero" }
                - { label: "Sobre",         value: "about" }
                - { label: "Cardápio",      value: "menu" }
                - { label: "Decorações",    value: "decorations" }
                - { label: "Galeria",       value: "gallery" }
                - { label: "Personalizado", value: "custom" }
                - { label: "Informações",   value: "policies" }
                - { label: "FAQ",           value: "faq" }

  # =======================
  # BANNER (HERO)
  # =======================
  - name: hero
    label: "Banner (Hero)"
    delete: false
    files:
      - file: "content/hero.json"
        name: hero
        label: "Conteúdo do Banner"
        format: json
        fields:
          - { label: "Título",    name: title,    widget: string }
          - { label: "Subtítulo", name: subtitle, widget: text, required: false }
          - { label: "Imagem do banner", name: image, widget: image, required: false, hint: "Tamanho recomendado ~1440×900." }
          - { label: "Overlay do banner (ex.: linear-gradient(...))", name: overlay, widget: string, required: false, hint: "Controla o escurecimento por cima da imagem." }
          - label: "Botão do banner"
            name: cta
            widget: object
            collapsed: true
            fields:
              - { label: "Texto", name: label, widget: string, required: false, default: "Ver Cardápio" }
              - { label: "Link",  name: href,  widget: string, required: false, default: "#menu" }

  # =======================
  # SOBRE
  # =======================
  - name: about
    label: "Sobre"
    delete: false
    files:
      - file: "content/about.json"
        name: about
        label: "Conteúdo do Sobre"
        format: json
        fields:
          - { label: "Título", name: title, widget: string }
          - { label: "Texto",  name: text,  widget: text }
          - { label: "Imagem", name: image, widget: image, required: false, hint: "Foto da seção Sobre." }
          - label: "Diferenciais (opcional)"
            name: features
            widget: list
            collapsed: true
            fields:
              - { label: "Ícone",  name: icon,  widget: image, required: false }
              - { label: "Título", name: title, widget: string }
              - { label: "Texto",  name: text,  widget: text }

  # =======================
  # CATEGORIAS
  # =======================
  - name: categories
    label: "Categorias do Cardápio"
    files:
      - file: "content/categories.json"
        name: categories
        label: "Categorias"
        format: json
        fields:
          - label: "Itens"
            name: items
            widget: list
            fields:
              - { label: "ID (fixo, minúsculo)", name: id,   widget: string, hint: "Ex.: especiais, tradicionais. Não alterar depois." }
              - { label: "Nome exibido",         name: name, widget: string, hint: "Ex.: Especiais, Tradicionais." }

  # =======================
  # PRODUTOS
  # =======================
  - name: products
    label: "Produtos"
    files:
      - file: "content/products.json"
        name: products
        label: "Lista de Produtos"
        format: json
        fields:
          - label: "Itens"
            name: items
            widget: list
            allow_add: true
            summary: "{{name}} — {{price}}"
            fields:
              - { label: "Ativo",        name: active,      widget: boolean, default: true, required: false, hint: "Desligue para esconder o produto sem apagar." }
              - { label: "Nome",         name: name,        widget: string }
              - { label: "Descrição",    name: description, widget: text, required: false }
              - { label: "Categoria",    name: category,    widget: select, required: false, options: ["", "especiais", "tradicionais"], hint: "Selecione a categoria ou deixe em branco." }
              - { label: "Preço",        name: price,       widget: string, required: false, hint: "Ex.: R$ 90" }
              - { label: "Imagem",       name: image,       widget: image,  required: false, hint: "Foto do produto." }
              - label: "Tamanhos (opcional)"
                name: sizes
                widget: list
                required: false
                fields:
                  - { label: "Nome do tamanho",  name: label, widget: string, hint: "Ex.: P, M, G" }
                  - { label: "Preço",            name: price, widget: string, required: false, hint: "Ex.: R$ 120" }
              - { label: "Selo (opcional)", name: badge, widget: select, required: false, options: ["Novo", "Mais vendido", "Promoção"] }
              - { label: "Ordem (opcional)", name: order, widget: number, required: false, hint: "Use para controlar a ordem." }

  # =======================
  # DECORAÇÕES
  # =======================
  - name: decorations
    label: "Decorações"
    files:
      - file: "content/decorations.json"
        name: decorations
        label: "Decorações"
        format: json
        fields:
          - { label: "Título",    name: title,    widget: string, required: false }
          - { label: "Subtítulo", name: subtitle, widget: text,   required: false }
          - label: "Itens"
            name: items
            widget: list
            summary: "{{caption}}"
            fields:
              - { label: "Imagem",  name: image,   widget: image, hint: "Ex.: images/gallery1.png" }
              - { label: "Legenda (opcional)", name: caption, widget: string, required: false }

  # =======================
  # GALERIA (opcional)
  # =======================
  - name: gallery
    label: "Galeria (opcional)"
    files:
      - file: "content/gallery.json"
        name: gallery
        label: "Galeria"
        format: json
        fields:
          - label: "Itens"
            name: items
            widget: list
            fields:
              - { label: "Imagem", name: image, widget: image }
              - { label: "Descrição/ALT (opcional)", name: alt, widget: string, required: false, hint: "Ajuda no Google e acessibilidade." }

  # =======================
  # INFORMAÇÕES / POLÍTICAS
  # =======================
  - name: policies
    label: "Informações / Políticas"
    files:
      - file: "content/policies.json"
        name: policies
        label: "Informações / Políticas"
        format: json
        fields:
          - { label: "Título de introdução", name: introTitle, widget: string }
          - { label: "Texto de introdução",  name: introText,  widget: text }
          - label: "Blocos"
            name: items
            widget: list
            summary: "{{title}}"
            fields:
              - { label: "Título do bloco", name: title, widget: string }
              - label: "Itens do bloco"
                name: items
                widget: list
                field:
                  label: "Linha"
                  name: line
                  widget: string

  # =======================
  # FAQ
  # =======================
  - name: faq
    label: "FAQ"
    files:
      - file: "content/faq.json"
        name: faq
        label: "FAQ"
        format: json
        fields:
          - label: "Perguntas"
            name: items
            widget: list
            summary: "{{q}}"
            fields:
              - { label: "Pergunta", name: q, widget: string }
              - { label: "Resposta", name: a, widget: text }
